sudo: false
language: python
python:
  - "3.6-dev"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install Flask-Testing blinker coverage codecov
script:
  - python run.py tests
  - python run.py makemessages
  - python run.py compilemessages
after_success:
  - codecov
