sudo: false
language: python
python:
  - "3.6-dev"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - travis_retry pip install -r requirements.txt
env:
  - SITE_CONFIG="website.config.Testing"
script:
  - python --version
  - coverage run -m unittest discover -t ../
after_success:
  - coverage report
