sudo: false
language: python
python:
  - "3.6-dev"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install Flask-Testing blinker coverage codecov
env:
  - SITE_CONFIG="website.config.Testing"
script:
  - coverage run -m unittest discover -t ../
after_success:
  - coverage report
  - codecov
